- name: To install and enable nginx
  hosts: web
  become: yes
  tasks:
  - name: To install nginx
    ansible.module.package:
     name: nginx
     state: present

- name: To install and enable nginx
  hosts: web
  become: yes
  tasks:
  - name: To enable nginx
    ansible.module.service:
     name: nginx
     state: started
     enabled: yes
