- name: To take input from prompt
  hosts: web
  vars-prompt:
  - name: course
    prompt: please enter your course name
  - name: duration
    prompt: please enter your course duration
  - name: trainer
    prompt: please enter your trainer name
  tasks:
  - name: same again
    ansible.builtin.debug:
     msg: "Hi, i am learning {{course}} the duration is {{duration}} and trainer name is {{trainer}}"