- name: Vars from prompt
  hosts: web
  vars_prompt:
  - name: course
    prompt: Please enter your course name
    private: false
  - name: duration
    prompt: Please enter your course duartion
    private: false
  - name: trainer
    prompt: Please enter your trainer name
    private: false
  tasks:
  - name: same again
    ansible.builtin.debug: 
     msg: "Hi i am learning {{course}} the duration is {{duration}} and my trainer is {{trainer}}"