- name: Vars from files
  hosts: web
  vars_prompt:
  - name: course
    prompt: "Please enter your course name"
  tasks:
  - name: Vars from files
    ansible.builtin.debug:
     msg: "Hi, i am learning {{course}} the duration is {{duration}} and trainer name is {{trainer}}"