- name: nginx installation
  hosts: web
  become: yes
  tasks:
  - name: same again
    ansible.builtin.pacakge:
     name: nginx
     state: present
  - name: same again 2
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
