- name: nginx installation
  hosts: web
  become: yes
  tasks:
  - name: same again
    ansible.builtin.package:
     name: nginx
     state: present

- name: nginx start
  hosts: web
  become: yes
  tasks:
  - name: same again 2
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
