- name: Installing nginx
  hosts: web
  gather_facts: no
  become: yes
  vars:
    course: devops
    duration: 120 
    subjects:
    - linux
    - shell scripting
    - ansible
    - terraform
    - docker
    - kubernetes
    - jenkins
    map:
    - linux: shell
  tasks:
  - name: Installing nginx
    ansible.builtin.debug:
     msg: "{{course}} {{duration}} {{subjects}} {{map}}"

