- name: conditions
  hosts: web
  vars_prompt:
  - name: number
    prompt: please enter a number
    private: false
  tasks:
  - name: Conditions
    ansible.builtin.debug:
      msg: "The number you have entered is {{number}}, and it is greater than 10"
    when: number | int > 10

  - name: Conditions
    ansible.builtin.debug:
      msg: "The number you have entered is {{number}}, and it is less than 10"
    when: number | int < 10     