- name: Installing nginx
  hosts: web
  gather_facts: no
  tasks:
  - name: Installing nginx
    ansible.builtin.pacakge:
      name: nginx
      state: present

- name: Installing nginx
  hosts: web
  gather_facts: no
  tasks:
  - name: Installing nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
