- name: default values
  hosts: web
  become: yes
  vars_prompt:
   name: course
   prompt: Please enter your course name
   private: false
  
  tasks:
  - name: To set a default value
    ansible.builtin.debug:
     msg: "The course you have selected is {{course | default ('Ansible') }}"
      

   
