- name: To create ec2 instances and R53 records
  hosts: local
  connection: local
  vars:
   sg_id: "sg-083d3a3c37d3ca1bc"
   ami_id: "ami-09c813fb71547fc4f"
   subnet_id: "subnet-05ecfc2d741753c8e"
   instances:
   - mysql
   - backend
   - frontend
   zone: "app789.site"

  tasks:
  - name: to install boto3 botocore
    ansible.builtin.pip:
     name:
     - boto3
     - botocore
     executable: pip-3.9

  - name: To create ec2-instances
    amazon.aws.ec2_instance:
     name: "{{ item }}"
     vpc_subnet_id: "{{ subnet_id }}"
     instance_type: "t3.micro"
     securit_group: "{{ sg_id }}"
     image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2-instances